---
name: Qwiet pre-zero Demo1

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  Qwiet-Static-Analysis:
    runs-on: ubuntu-latest
    container: shiftleft/core:latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v4

    # - name: Download ShiftLeft CLI
    #   run: |
    #     curl https://cdn.shiftleft.io/download/sl > ./sl && chmod a+rx ./sl 
    
    - name: Run sl analyze 1
      shell: bash
      run: |
        sl analyze --verbose --wait --app "${GITHUB_REPOSITORY_OWNER}_${GITHUB_REPOSITORY#*/}" .
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}

    - name: Generate Sarif Report
      shell: bash
      run: |
        export SHIFTLEFT_ORG_ID="eba14690-d605-4f85-b5e3-b2992e9174b0"
        sl sarif export --app elangosenthilnathan_shiftleft-python-demo --report-file sarif.json

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: sarif.json  
        category: qwiet-prezero   
