---
# This workflow integrates ShiftLeft NG SAST with GitHub
# Visit https://docs.shiftleft.io for help
name: ShiftLeft

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > sl && chmod a+rx sl

    - name: Install reqs
      run: |
        pip install -r requirements.txt

    - name: NextGen Static Analysis
      uses: mathiasvr/command-output@v2.0.0
      id: scanID
      with: 
        run: |
          ./sl analyze --wait --app shiftleft-python-demo --pythonsrc $(pwd) | sed 's/The Scan ID for application.*/(&)/g'
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}

    - name: Get ScanID
      run:
        echo ScanID is ${{ steps.scanID.outputs.stdout }}
        


  
