# This workflow integrates ShiftLeft NG SAST with GitHub
# Visit https://docs.shiftleft.io for help
name: ShiftLeft

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > sl && chmod a+rx sl

    - name: SAST-Scan
      run: |
        pip install -r requirements.txt
        ./sl analyze --wait --app shiftleft-python-demo --pythonsrc $(pwd) > slout.txt
        sed -i -n 's/\(The Scan ID for application.*:\)\(.*\)/\2/p' slout.txt
        cat slout.txt
        echo "scanID=$(cat slout.txt)" >> $GITHUB_OUTPUT
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}

        
    - name: Print ScanID
      run: |
        echo "Scan ID is ${{ steps.SAST-Scan.outputs.scanID }}"

  
